// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbYRlb4vlrPhdnqNSRrjfanQP0uL31dyk',
    appId: '1:751108742545:web:a93db620e8aad6412b4e30',
    messagingSenderId: '751108742545',
    projectId: 'viziteaza-oradea',
    authDomain: 'viziteaza-oradea.firebaseapp.com',
    storageBucket: 'viziteaza-oradea.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwcDkIXfvxLNE4U6Yo4Es6BYxesU41NA0',
    appId: '1:751108742545:ios:062a1fc2c4266a152b4e30',
    messagingSenderId: '751108742545',
    projectId: 'viziteaza-oradea',
    storageBucket: 'viziteaza-oradea.firebasestorage.app',
    iosBundleId: 'com.example.viziteazaOradea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbYRlb4vlrPhdnqNSRrjfanQP0uL31dyk',
    appId: '1:751108742545:web:c87a6ad0bc83011e2b4e30',
    messagingSenderId: '751108742545',
    projectId: 'viziteaza-oradea',
    authDomain: 'viziteaza-oradea.firebaseapp.com',
    storageBucket: 'viziteaza-oradea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwcDkIXfvxLNE4U6Yo4Es6BYxesU41NA0',
    appId: '1:751108742545:ios:e82bdb0556ede5732b4e30',
    messagingSenderId: '751108742545',
    projectId: 'viziteaza-oradea',
    storageBucket: 'viziteaza-oradea.firebasestorage.app',
    iosBundleId: 'ro.viziteaza.oradea',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxwp_gEo3Qj8q8I2CRPy-Nb8Vb7mxy2gQ',
    appId: '1:751108742545:android:20334bbc59eff17d2b4e30',
    messagingSenderId: '751108742545',
    projectId: 'viziteaza-oradea',
    storageBucket: 'viziteaza-oradea.firebasestorage.app',
  );

}